### ISSUE TITLE
use Coinbase paymaster infrastructure

### ISSUE THREAD

**Issue by xh3b4sd** [uvio-network/issues#49]
We are using the Biconomy infra right now and it works, but it is not inspiring a lot of confidence. Plus, we want to focus on Base as an ecosystem and the integration between Coinbase and Base will just become stronger and more polished over time. The shift over shouldn't be too hard, there is just a bunch of legwork to be done. For this task we can also reach out to https://warpcast.com/nickprince.eth. 

https://docs.cdp.coinbase.com/paymaster/docs/paymaster-bundler-qs-headless

---

**update**

At the moment we are stuck with technical issues. We should maybe reconsider this issue and prevent any form of vendor lock in since Coinbase does not appear to support other L2s with their bundler and paymaster infrastructure.

An alternative would be to upgrade to the Nexus SDK, which looks similar in the frontend to what we already prototyped. See https://docs.biconomy.io/nexus/tutorials/gasless.

**Comment by xh3b4sd** [comment]
```
ResourceUnavailableRpcError: Requested resource not available.

URL: https://api.developer.coinbase.com/rpc/v1/base-sepolia/cA3ju6qGr4nqtgjBIMmXNKIlGHjmFBzi
Request body: {
  "method": "pm_getPaymasterData",
  "params": [
    {
      "callData": "0x34fcd5be0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000120000000000000000000000000484c32b1288a88a48f8e7d20173a1048589df182000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000206ab72edea55819a9a90622873976a79d3419e300000000000000000000000000000000000000000000000021dc9f1283f4000000000000000000000000000000000000000000000000000000000000000000000000000000000000206ab72edea55819a9a90622873976a79d3419e30000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001446e43e8240000000000000000000000000000000000000000000000000006257a6283c86900000000000000000000000000000000000000000000000021dc9f1283f400000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000006720258000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000004039396634393865616533633130616233336139366138393338323532376336363631643731363962336265646231316639316564316438346430626239643266000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "callGasLimit": "0x5b9b1",
      "initCode": "0x0ba5ed0c6aa8c49038f819e587e2633c4a9f428a3ffba36f00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000020000000000000000000000000f1c1cfeA5814EE199e12aa1660e1f5e929fA6F2d",
      "maxFeePerGas": "0x165a0bc00",
      "maxPriorityFeePerGas": "0x1dcd6500",
      "nonce": "0x192cf7561b70000000000000000",
      "paymasterAndData": "0x709a4bae3db73a8e717aefca13e88512f738b27f0000671e954d000000000000434e0e7b79e4422c8b0e8c2850e852d1010100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006978fffffffffffffffffffffffffffffff0000000000000000000000000000000007aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1c",
      "preVerificationGas": "0xef47",
      "sender": "0x584f6E8Cde690CA74d0BA952B877BaB712bfC628",
      "signature": "0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000041fffffffffffffffffffffffffffffff0000000000000000000000000000000007aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1c00000000000000000000000000000000000000000000000000000000000000",
      "verificationGasLimit": "0x4b19f"
    },
    "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789",
    "0x14a34",
    null
  ]
}

Details: request denied - max global sponsorship limit reached - userOperation cost 20.264 USD
Version: 2.21.11
    at delay.count.count (buildRequest.js:61:31)
    at async attemptRetry (withRetry.js:17:30)Caused by: RpcRequestError: RPC Request failed.
```

**Comment by xh3b4sd** [comment]
```
import * as Privy from "@privy-io/react-auth";

import { Address, Hex } from "viem";
import { ChainStore } from "@/modules/chain/ChainStore";
import { BundlerClient, createBundlerClient, toCoinbaseSmartAccount } from "viem/account-abstraction";
import { createWalletClient } from "viem";
import { custom } from "viem";
import { http } from "viem";
import { NewPublicClient } from "@/modules/chain/PublicClient";
import { parseGwei } from "viem";
import { PublicClient } from "viem";
import { Receipt } from "@/modules/wallet/WalletInterface";
import { Signer } from "@/modules/wallet/WalletInterface";
import { Transaction } from "@/modules/transaction/TransactionInterface";
import { toAccount } from "viem/accounts";

export const NewWalletEmbedded = async (wal: Privy.ConnectedWallet, index: number = 0): Promise<Signer> => {
  const active = ChainStore.getState().getActive();
  const provider = await wal.getEthereumProvider();

  const add = wal.address as Address;

  const cli = createWalletClient({
    chain: active,
    transport: custom(provider),
  });

  const loc = toAccount({
    address: add,

    // Use wallet client to sign a message
    async signMessage({ message }) {
      return await provider.request({
        method: 'personal_sign',
        params: [message, add],
      });
    },

    // Use wallet client to sign a transaction
    async signTransaction(transaction) {
      return await provider.request({
        method: 'eth_signTransaction',
        params: [transaction],
      });
    },

    // Use wallet client to sign typed data
    async signTypedData(typedData) {
      return await provider.request({
        method: 'eth_signTypedData_v4',
        params: [add, JSON.stringify(typedData)],
      });
    },
  });

  const acc = await toCoinbaseSmartAccount({
    client: cli,
    owners: [loc],
  })

  const bun = createBundlerClient({
    account: acc,
    client: cli,
    transport: http(active.coinbasePaymasterEndpoint),
    chain: active,
  });

  return new Embedded(bun.account.address, bun, NewPublicClient());
};

class Embedded implements Signer {
  private add: Address;
  private bun: BundlerClient;

  constructor(add: Address, bun: BundlerClient, pub: PublicClient) {
    this.add = add;
    this.bun = bun;

    this.bun.userOperation = {
      async estimateFeesPerGas(parameters) {
        const estimatedFees = await pub.estimateFeesPerGas();
        return {
          ...estimatedFees,
          maxFeePerGas: BigInt(
            Math.round(Number(estimatedFees.maxFeePerGas) * 1.12)
          ),
          maxPriorityFeePerGas: BigInt(
            Math.round(Number(estimatedFees.maxPriorityFeePerGas) * 1.12)
          ),
        };
      },
    };
  }

  address(): Address {
    return this.add;
  }

  connectorType(): string {
    return "embedded";
  }

  async sendTransaction(txn: Transaction[], bef: () => void, aft: () => void): Promise<Receipt> {
    {
      bef();
    }

    const hsh = await this.bun.sendUserOperation({
      calls: txn.map((x) => {
        return {
          to: x.to as Address,
          data: x.data as Hex,
        };
      }),
      maxFeePerGas: parseGwei("6"),
      maxPriorityFeePerGas: parseGwei("0.5"),
      paymaster: true,
    });

    {
      aft();
    }

    const { receipt, success } = await this.bun.waitForUserOperationReceipt({
      hash: hsh,
    });

    return {
      hash: receipt.transactionHash,
      rejected: false,
      success: success,
    };
  }
}
```
